### ISSUE TITLE
docs: cleanup

### ISSUE THREAD

**Issue by ajay-gov** [swimos/swimos-docs#101]
- [x] Add content to reference cards with no text
- [x] Change  titles and sub-section titles on new content (agent granularity, lane organization etc.)
- [x]  Change swim library references from 4.0.1 to 4.1.0.x once they are released

**Comment by ajay-gov** [comment]
Will create a new issue for updating docs to 4.1.0.x

**Comment by afolson** [comment]
@ajay-gov Last item is merged so I think this can be closed? https://github.com/swimos/swimos-docs/pull/105
