### ISSUE TITLE
Blog: Handling JSON data with Swim

### ISSUE THREAD

**Issue by SirCipher** [swimos/swimos-docs#128]

**Comment by StreamingDataApps** [comment]
Ooops, I should have opened a PR I guess, I commited to #127...
https://github.com/swimos/swimos-docs/commit/68cf0b95d49fbdbf4f6fd9e50972754c36db67af

**Comment by StreamingDataApps** [comment]
PR opened here:
https://github.com/swimos/swimos-docs/pull/140
