### ISSUE TITLE
Blog: Reddit bot overview

### ISSUE THREAD

**Issue by SirCipher** [swimos/swimos-docs#151]
At minimum, we should probably cover:

- [x] What `munin` does
   - Assigns an answer to every r/WhatsThisBird submission based on the comments to that submission
      - Most comments are analyzed within the server itself, but some require external API calls (to eBird.org)
   - Pushes every answer to a PostgreSQL database
   - Posts a comment to the submission with the (possibly in-progress) answer; leaves at most one comment per submission, editing the comment if necessary or deleting it if the submission is deleted/removed
- [x] Ease of implementing `munin` as a Swim server (business logic completely runtime-independent, external clients embed trivially, event-driven model, self-managed state so the database is "write-only")
- [x] Showcase how a Swim server can serve plain REST data "for free" through HTTP lanes:
   - https://munin.swim.services/submissions?lane=api/answered
   - https://munin.swim.services/submissions?lane=api/unanswered
   - https://munin.swim.services/submissions?lane=api/reviewed
   - https://munin.swim.services/submissions?lane=api/unreviewed

I added a [long message](https://swim-it.slack.com/archives/C052LQ2LUJY/p1705529080410969) in the `#dx` Slack channel that contains several ideas, but we definitely should limit the scope for a first pass.

**Comment by StreamingDataApps** [comment]
Under review: https://github.com/swimos/swimos-docs/pull/157

**Comment by ajay-gov** [comment]
@SirCipher can you review #157, @StreamingDataApps has made the changes you requested.
