### ISSUE TITLE
Jekyll alert section template

### ISSUE THREAD

**Issue by SirCipher** [swimos/swimos-docs#171]
It would be useful to extend the `alert.html` liquid template (if that's the right name for it?) and add support for:
- Ok: https://fontawesome.com/v3/icon/ok-sign
- Bad: https://fontawesome.com/v3/icon/remove-sign
- Warning: https://fontawesome.com/v3/icon/warning-sign

Additionally, the default colour for links within the alert template renders them very dark.

Attached is a screenshot where the link colour has been overridden. 

![Screenshot 2024-03-20 at 16 51 36](https://github.com/swimos/swimos-docs/assets/6685353/5f027bf1-b35d-4389-aa3b-5902d2b0328b)

If it's useful, the code for the above template is:

```
{% capture alert_text %}
Any type parameters used by a Lane must implement the <a href="https://doc.rust-lang.org/std/marker/trait.Send.html" style="color: lightblue; font-weight: bold;">Send</a> and <a href="{% link _rust_backend/forms.md %}" style="color: lightblue; font-weight: bold;">Form</a> traits.
{% endcapture %}

{% include alert.html title='Note' text=alert_text %}```

**Comment by afolson** [comment]
Closed by https://github.com/swimos/swimos-docs/pull/201
