### ISSUE TITLE
All links are broken

### ISSUE THREAD

**Issue by jcustenborder** [swimos/swimos-docs#205]
**Describe the bug**

All of the links result in a 404. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jcustenborder** [comment]
Everything under https://www.swimos.org/server/java/ is a broken link.

**Comment by afolson** [comment]
Fixed in https://github.com/swimos/swimos-docs/pull/206
