### ISSUE TITLE
Process Monitor Application: Tutorial

### ISSUE THREAD

**Issue by ajay-gov** [swimos/swimos-docs#63]
Create a second tutorial and use the Process Monitor application from [here](https://github.com/swiminc/swim-monitor) as the reference. The application should get info on the processes running on the machine thereby generating data without the need for an external data source

- [ ]  Two agent types: Process Agent and a Host Agent 
- [ ]  Add a real-time table to display Processes for a Host (similar to the output of a `top` command)

**Comment by ajay-gov** [comment]
@StreamingDataApps are these two tasks done? If so can we mark them as done?

**Comment by StreamingDataApps** [comment]
Here is version two of the process monitor tutorial:
https://github.com/swimos/swimos-docs/pull/138
