### ISSUE TITLE
docs: Introspection reference guide

### ISSUE THREAD

**Issue by ajay-gov** [swimos/swimos-docs#79]
- [x]  Show an app with the `MetaKernel` in the `server.recon`
- [x]  Generate data into a few Web Agents and demonstrate the introspection APIs i.e get all node types, nodes of a given type, lanes for a give node, pulse etc. with the swim-cli
- [ ]  Also show `swim-cli reflect` command

**Comment by ajay-gov** [comment]
Should this be a Reference Guide or a How-To-Guide. Any thoughts @afolson @PiggottDev @brohitbrose ?

**Comment by afolson** [comment]
@ajay-gov This one feels like a how-to guide as written, but we probably need a reference guide at some point as well.

**Comment by ajay-gov** [comment]
@afolson i think so too. Maybe we should change it to the How-To-Guide. I feel that the how-to guide in this format is easier to do and more usable. We can add a comprehensive introspection reference guide later.
